# Generated by: PML v0.7.8 Beta Hamid Alipour blog.code-head.com
# -*- coding: UTF-8 -*-

sys.stdout.write("""<html>
	<head>
		<title>""")
sys.stdout.write(pml.get("title"))
sys.stdout.write("""</title>
	</head>
	<body>
		<u>""")
sys.stdout.write(pml.get("title"))
sys.stdout.write("""</u><br/>
		""")
for drink in pml.get("drinks"):
    sys.stdout.write("""
			""")
    sys.stdout.write(drink)
    sys.stdout.write("""<br/>
		""")
sys.stdout.write("""
	</body>
</html>
""")
